In [2]:
from google.colab import drive
drive.mount('/content/grdive')

Drive already mounted at /content/grdive; to attempt to forcibly remount, call drive.mount("/content/grdive", force_remount=True).


In [0]:
import pandas as pd
import numpy as np
import math 
from collections import deque
from numpy import array
import random

In [0]:
df =pd.read_excel('/content/grdive/My Drive/CFD Machine Learning/CFD.xlsx')

In [71]:
df[:]

ccx        ccy        ccz  ...        U2        U3   distance
276101  -3.549367   0.873805   0.165214  ...  0.312564  0.086993   3.659076
276075  -3.549369  -0.873805   0.165215  ...  0.425258  0.081138   3.659077
276008  -0.873900  -3.549809   0.165215  ...  0.322960  0.072068   3.659527
276166  -0.873901   3.549815   0.165213  ...  0.301015  0.068508   3.659534
2717     0.873998   3.550097   0.165215  ...  0.066385  0.019641   3.659830
276020   0.873998  -3.550097   0.165215  ...  0.084345  0.033828   3.659830
2365     3.550562   0.874096   0.165215  ...  0.067213 -0.004526   3.660305
276081   3.550562  -0.874096   0.165215  ...  0.469799 -0.036332   3.660305
2022    -3.171205  -1.838501   0.165493  ...  0.711182  0.071588   3.669334
276122  -3.171205   1.838503   0.165493  ...  0.585344  0.076908   3.669335
1845    -1.838588  -3.171412   0.165492  ...  0.638383  0.068604   3.669557
276149  -1.838586   3.171413   0.165491  ...  0.574993  0.067115   3.669557
276039   1.838924  -3.171949   0.165492  ...  0.046744 -0.038786   3.670189
276151   1.838926   3.171952   0.165493  ...  0.039359 -0.056248   3.670193
276124   3.172170   1.839009   0.165492  ...  0.154011 -0.027047   3.670423
276064   3.172170  -1.839011   0.165492  ...  0.430632  0.008234   3.670424
276105  -3.547741   0.874263   0.499513  ...  0.335237  0.121523   3.687861
276079  -3.547743  -0.874263   0.499512  ...  0.454766  0.116399   3.687862
276012  -0.874355  -3.548183   0.499510  ...  0.366379  0.126965   3.688307
276170  -0.874358   3.548190   0.499513  ...  0.334115  0.117156   3.688315
276184   0.874456   3.548471   0.499510  ...  0.051430  0.045055   3.688608
276024   0.874456  -3.548471   0.499510  ...  0.075397  0.076303   3.688608
276085   3.548938  -0.874551   0.499510  ...  0.474620 -0.001005   3.689080
276111   3.548938   0.874551   0.499510  ...  0.070300  0.040818   3.689080
276046  -2.768935  -2.441561   0.166028  ...  0.782648  0.063859   3.695374
276134  -2.768933   2.441566   0.166029  ...  0.690687  0.060777   3.695376
276034  -2.441578  -2.768997   0.166029  ...  0.733185  0.061510   3.695431
2625    -2.441578   2.769000   0.166029  ...  0.667888  0.060604   3.695434
276042   2.442150  -2.769597   0.166028  ...  0.021274 -0.000362   3.696258
276153   2.442150   2.769598   0.166029  ...  0.085434  0.000548   3.696260
...           ...        ...        ...  ...       ...       ...        ...
266909  47.666650 -13.666650  39.000000  ...  0.009181  0.125522  63.086344
270845  47.666650  13.666650  39.000000  ...  0.025423  0.122113  63.086344
271805  47.666650 -11.666650  39.666650  ...  0.000472  0.121237  63.100423
275165  47.666650  11.666650  39.666650  ...  0.038231  0.131068  63.100423
266525  47.666650  15.666650  38.333350  ...  0.014984  0.126803  63.142689
262013  47.666650 -15.666650  38.333350  ...  0.014148  0.138098  63.142689
271420  47.000000 -14.333350  39.666650  ...  0.010970  0.129720  63.149727
275548  47.000000  14.333350  39.666650  ...  0.024766  0.118924  63.149727
271709  47.666650 -12.333350  39.666650  ...  0.003098  0.122770  63.227084
275261  47.666650  12.333350  39.666650  ...  0.034536  0.128563  63.227084
266813  47.666650 -14.333350  39.000000  ...  0.013236  0.128506  63.234124
270941  47.666650  14.333350  39.000000  ...  0.022857  0.120139  63.234124
271324  47.000000 -15.000000  39.666650  ...  0.016012  0.139533  63.304369
275644  47.000000  15.000000  39.666650  ...  0.025251  0.120226  63.304369
275357  47.666650  13.000000  39.666650  ...  0.030391  0.125559  63.360498
271613  47.666650 -13.000000  39.666650  ...  0.005819  0.124484  63.360498
271037  47.666650  15.000000  39.000000  ...  0.021635  0.122510  63.388560
266717  47.666650 -15.000000  39.000000  ...  0.020162  0.137273  63.388560
271228  47.000000 -15.666650  39.666650  ...  0.010697  0.145299  63.465637
275740  47.000000  15.666650  39.666650  ...  0.018457  0.129334  63.465637
271517  47.666650 -13.666650  39.666650  ...  0.008532  0.1265

In [0]:
df=df.iloc[:,3:9]

In [7]:
df.head()

ccx       ccy       ccz        U1        U2        U3
0 -15.66665 -15.66665  0.333333  1.000053  0.000269  0.000074
1 -15.00000 -15.66665  0.333333  1.000582  0.000954  0.000260
2 -14.33335 -15.66665  0.333333  1.001449  0.001724  0.000427
3 -13.66665 -15.66665  0.333333  1.002579  0.002579  0.000593
4 -13.00000 -15.66665  0.333333  1.003905  0.003499  0.000760

In [0]:
df['distance']=np.sqrt((df['ccx']**2)+(df['ccy']**2)+(df['ccz']**2))

In [9]:
df.head()

ccx       ccy       ccz        U1        U2        U3   distance
0 -15.66665 -15.66665  0.333333  1.000053  0.000269  0.000074  22.158496
1 -15.00000 -15.66665  0.333333  1.000582  0.000954  0.000260  21.692281
2 -14.33335 -15.66665  0.333333  1.001449  0.001724  0.000427  21.236760
3 -13.66665 -15.66665  0.333333  1.002579  0.002579  0.000593  20.792603
4 -13.00000 -15.66665  0.333333  1.003905  0.003499  0.000760  20.360625

In [0]:
df=df.sort_values('distance')

In [11]:
df.head()

ccx       ccy       ccz        U1        U2        U3  distance
276101 -3.549367  0.873805  0.165214  0.157078  0.312564  0.086993  3.659076
276075 -3.549369 -0.873805  0.165215  0.186573  0.425258  0.081138  3.659077
276008 -0.873900 -3.549809  0.165215  1.250538  0.322960  0.072068  3.659527
276166 -0.873901  3.549815  0.165213  1.157566  0.301015  0.068508  3.659534
2717    0.873998  3.550097  0.165215  0.683874  0.066385  0.019641  3.659830

In [0]:
X=df.iloc[:,3:7].values

In [13]:
X.shape

(346167, 4)

In [0]:
#X=X[0:22000]

In [0]:
X=X[:,0:3]

In [16]:
X[0]

array([0.15707782, 0.31256394, 0.08699269])

In [0]:
sequential_data=[]
nearby_velocities =deque(maxlen=101)

In [0]:
#Creates the complete sequential data to be split into train and test sequences
for i in range(0,len(X)-1):
  nearby_velocities.append([n for n in X[i]])
  if len(nearby_velocities) ==101:
    sequential_data.append([np.array(nearby_velocities),np.array(nearby_velocities[50])])

    

In [19]:
len(sequential_data)

346066

In [20]:
sequential_data

Output hidden; open in https://colab.research.google.com to view.

In [0]:
random.shuffle(sequential_data)

In [22]:
#AFTER SHUFFLING
sequential_data

Output hidden; open in https://colab.research.google.com to view.

In [0]:
X_train=array([n[0] for n in sequential_data[0:20000]])
X_validate=array([n[0] for n in sequential_data[20000:22000]])

In [24]:
print(X_train.shape)
print(X_validate.shape)

(20000, 101, 3)
(2000, 101, 3)


In [0]:
#X_train=np.delete(X_train,50,1) #The first number 50 is index value and 1 means 2nd dimension
#X_validate=np.delete(X_validate,50,1)

In [26]:
print(X_train.shape)
print(X_validate.shape)

(20000, 100, 3)
(2000, 100, 3)


In [0]:
Y_train=array([n[1] for n in sequential_data[0:20000]])
Y_validate=array([n[1] for n in sequential_data[20000:22000]])  #Y_test will be used for validation

In [28]:
print(Y_train.shape)
print(Y_validate.shape)

(20000, 3)
(2000, 3)


In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:
sc_X=StandardScaler()
sc_Y=StandardScaler()

In [0]:
X_train[:,:,1]=sc_X.fit_transform(X_train[:,:,1])
X_train[:,:,0]=sc_X.fit_transform(X_train[:,:,0])
X_train[:,:,2]=sc_X.fit_transform(X_train[:,:,2])

In [0]:
X_validate[:,:,1]=sc_X.fit_transform(X_validate[:,:,1])
X_validate[:,:,0]=sc_X.fit_transform(X_validate[:,:,0])
X_validate[:,:,2]=sc_X.fit_transform(X_validate[:,:,2])

In [33]:
X_train

array([[[-1.76189576,  0.34568104, -0.38289055],
        [-1.75109863,  0.81202963, -0.38975975],
        [-0.21472856,  0.86945198, -0.25593407],
        ...,
        [ 0.59671256,  4.17212048, -0.21610954],
        [ 0.43249425,  3.63008846, -0.21648517],
        [ 1.09394425,  3.46369395, -0.20450057]],

       [[-0.51887069, -0.70874268, -0.28325983],
        [-0.56197857, -0.76261839, -0.28966892],
        [-0.66350711, -0.7402436 , -0.31082816],
        ...,
        [-0.59794988, -0.6405061 , -0.30788328],
        [-0.67717353, -0.74711414, -0.30859011],
        [-0.682392  , -0.72980079, -0.30768277]],

       [[-1.29334115, -0.77461058,  5.16655002],
        [-1.08860434, -0.35434071,  5.23776061],
        [-1.0997894 , -0.36277976,  5.17466579],
        ...,
        [-1.05258929,  0.09326407,  3.48086949],
        [ 1.40086839,  1.21391271, -0.21147668],
        [ 1.60637748,  1.47169633, -0.21225307]],

       ...,

       [[-1.45588126, -0.37603201,  0.28442579],
        [ 0

In [0]:
Y_train=sc_Y.fit_transform(Y_train)
Y_validate=sc_Y.fit_transform(Y_validate)

In [0]:
                                    #RECURSIVE DEEP NEURAL NETWORK

import torch
import torch.nn as nn
import torchvision.datasets as datasets  #import the dataset
import torchvision.transforms as transforms  #
from torch.autograd import Variable  #autograd is a part of pytorch 0.3 but can also be used with pytorch 0.4
from torch.utils.data import Dataset
import sys

In [0]:
                                    #CONVERT NUMPY TO PYTORCH 
X_train=torch.tensor(X_train)
Y_train=torch.tensor(Y_train)
X_validate=torch.tensor(X_validate)
Y_validate=torch.tensor(Y_validate)
#CONVERT PYTORCH TENSOR TO VARIABLE FORMAT
X_validate=Variable(X_validate)
Y_validate=Variable(Y_validate)

In [37]:
print(X_train.shape)
print(X_validate.shape)

torch.Size([20000, 100, 3])
torch.Size([2000, 100, 3])


In [0]:
#WHEN WE ARE USING OUR OWN DATASET THEN WE NEED TO CREATE A DATASET CLASS WHICH INHERITS FROM PREDEFINED 
#DATASET CLASS OF torch.utils.data library
class Dataset(Dataset):
  def __init__(self,x,y):
    self.x=x
    self.y=y
  
  def __getitem__(self,index):
    return self.x[index], self.y[index]
  
  def __len__(self):
    return len(self.x)

In [0]:
train_dataset=Dataset(X_train,Y_train)
validate_dataset=Dataset(X_validate,Y_validate)

In [40]:
print(train_dataset.x.shape)
print(train_dataset.y.shape)
print(validate_dataset.x.shape)
print(validate_dataset.y.shape)

torch.Size([20000, 100, 3])
torch.Size([20000, 3])
torch.Size([2000, 100, 3])
torch.Size([2000, 3])


In [0]:
#MAKE DATA ITERABLE BY LOADING IT TO A LOADER. Shuffe the data to make it independent of order
#Batch size is the number of elements in a batch
train_loader=torch.utils.data.DataLoader(dataset=train_dataset,
                                        batch_size=200,
                                        shuffle=True)

In [0]:
#MAKE DATA ITERABLE BY LOADING IT TO A LOADER. Shuffe the data to make it independent of order
#Batch size is the number of elements in a batch
validation_loader=torch.utils.data.DataLoader(dataset=validate_dataset,
                                        batch_size=200,
                                        shuffle=False)

In [43]:
len(validation_loader)

10

In [44]:
#THIS IS ONLY FOR DISPLAY PURPOSE TO UNDERSTAND THE DATA
print("There is {} batches in the dataset".format(len(train_loader)))
shown=0
for (x,y) in train_loader:
  if shown==1:
    break
  print("For one batch there is:")
  print("Data: {}, Type: {} ".format(x.shape,x.dtype))
  print("Data: {}, Type: {} ".format(y.shape,y.dtype))
  shown+=1
  

There is 100 batches in the dataset
For one batch there is:
Data: torch.Size([200, 100, 3]), Type: torch.float64 
Data: torch.Size([200, 3]), Type: torch.float64 


In [0]:
#Input of neural net 2 nodes and output of the neural net is 3 nodes
# Neural Net using 3 hidden layers each containing 3 nodes 

input_size=3
hidden_size=3

class Model(nn.Module):
  def __init__(self):
    super(Model,self).__init__()
    self.bi_rcnn1=torch.nn.LSTM(input_size=3, hidden_size=3, num_layers=1, batch_first=False, bidirectional=True)   
    self.fc1=torch.nn.Linear(6,3)
              
    
    #Input hidden hidden output  =>layer format
  def forward(self,x):
      out,hidden=self.bi_rcnn1(x)  
      out=out[:,50]  #Middle value-1 6 input values to fully connected layer
      out=self.fc1(out)
      return out  
  
  def init_hidden(self):
      # Initialize hidden and cell states
      # (num_layers * num_directions, batch, hidden_size)
      return Variable(torch.zeros(1, 200, 3))

    

In [0]:
# Instantiate RNN model
model = Model()

In [47]:
print(model.parameters)

<bound method Module.parameters of Model(
  (bi_rcnn1): LSTM(3, 3, bidirectional=True)
  (fc1): Linear(in_features=6, out_features=3, bias=True)
)>


In [48]:
criterion=torch.nn.MSELoss(size_average=True)   #Loss Criterion
optimizer=torch.optim.Adam(model.parameters(),lr=0.01)

/usr/local/lib/python3.6/dist-packages/torch/nn/_reduction.py:46: UserWarning: size_average and reduce args will be deprecated, please use reduction='mean' instead.
  warnings.warn(warning.format(ret))


In [49]:
epochs=100   #We have done it for 100 epochs 
for epoch in range(epochs):
  for x, y in train_loader:
    x=Variable(x.float())
    y=Variable(y.float())
    outputs=model(x)
    optimizer.zero_grad()
    
    loss=criterion(outputs,y)
    loss.backward()
    optimizer.step()
  
  print("EPOCH {} COMPLETED".format(epoch))
  print("Training loss: {}".format(loss.item()))

EPOCH 0 COMPLETED
Training loss: 0.7295355796813965
EPOCH 1 COMPLETED
Training loss: 0.5258730053901672
EPOCH 2 COMPLETED
Training loss: 0.7450513243675232
EPOCH 3 COMPLETED
Training loss: 0.703131377696991
EPOCH 4 COMPLETED
Training loss: 0.7265751361846924
EPOCH 5 COMPLETED
Training loss: 0.7460402250289917
EPOCH 6 COMPLETED
Training loss: 0.6009770035743713
EPOCH 7 COMPLETED
Training loss: 0.6993603110313416
EPOCH 8 COMPLETED
Training loss: 0.5584316849708557
EPOCH 9 COMPLETED
Training loss: 0.7702839970588684
EPOCH 10 COMPLETED
Training loss: 0.7382069826126099
EPOCH 11 COMPLETED
Training loss: 0.5713150501251221
EPOCH 12 COMPLETED
Training loss: 0.6562929749488831
EPOCH 13 COMPLETED
Training loss: 0.6742871403694153
EPOCH 14 COMPLETED
Training loss: 0.41964834928512573
EPOCH 15 COMPLETED
Training loss: 0.5739167332649231
EPOCH 16 COMPLETED
Training loss: 0.7302465438842773
EPOCH 17 COMPLETED
Training loss: 0.6172370910644531
EPOCH 18 COMPLETED
Training loss: 0.832015872001648
EPOC

In [50]:
count=1
for x, y in validation_loader:
    x=Variable(x.float())
    y=Variable(y.float())
    outputs=model(x)
    
    for i,j in zip(outputs,y):
      print("Predicted "+str(i)+" Actual "+str(j))
    print("Batch: {} completed".format(count))
    count=count+1

Predicted tensor([-0.5262, -0.4732, -0.1282], grad_fn=<SelectBackward>) Actual tensor([-0.6395, -0.0575, -0.2142])
Predicted tensor([-0.6785,  0.9949, -0.2675], grad_fn=<SelectBackward>) Actual tensor([-1.3403, -0.2088, -0.5490])
Predicted tensor([ 0.6765, -0.0855, -0.2376], grad_fn=<SelectBackward>) Actual tensor([-0.5046, -0.7332, -0.2599])
Predicted tensor([ 0.5866, -0.0444, -0.1861], grad_fn=<SelectBackward>) Actual tensor([ 1.0905, -0.4907, -0.3404])
Predicted tensor([ 0.6092,  0.0170, -0.2088], grad_fn=<SelectBackward>) Actual tensor([ 1.5404,  0.1778, -0.3527])
Predicted tensor([ 0.7489,  0.0223, -0.1171], grad_fn=<SelectBackward>) Actual tensor([-0.6093, -0.7794, -0.2870])
Predicted tensor([-1.0700,  0.5017, -0.1024], grad_fn=<SelectBackward>) Actual tensor([-1.5136, -0.5655, -0.5332])
Predicted tensor([ 0.6043,  0.0084, -0.1922], grad_fn=<SelectBackward>) Actual tensor([ 1.6898,  0.1213, -0.2992])
Predicted tensor([0.5906, 0.4414, 0.0295], grad_fn=<SelectBackward>) Actual tens

In [0]:
outputs=sc_Y.inverse_transform(outputs.detach().numpy())
y=sc_Y.inverse_transform(y.detach().numpy())

In [52]:
#VELOCITY IN ACTUAL FORMAT AFTER INVERSE TRANSFORMATION FOR THE LAST BATCH ie for 200 observations
for i,j in zip(outputs,y):
  print("Predicted "+str(i)+" Actual "+str(j))

Predicted [0.80949694 0.08633223 0.17030495] Actual [0.21220477 0.09871712 0.01944595]
Predicted [0.14654349 0.22513364 0.3787018 ] Actual [ 0.05192093  0.09849536 -0.20631582]
Predicted [0.5341523  0.08004943 0.37939703] Actual [0.2949092  0.00810157 0.1672526 ]
Predicted [0.13626869 0.14793602 0.5223967 ] Actual [ 0.24533394  0.137076   -0.11882836]
Predicted [0.5840819  0.08329201 0.410675  ] Actual [0.29143423 0.0228524  0.0730285 ]
Predicted [0.6770322  0.12007566 0.48750973] Actual [0.173878   0.01444838 0.01581042]
Predicted [0.39587352 0.19294605 0.45150322] Actual [ 0.39031273  0.07303512 -0.03339923]
Predicted [0.5249918 0.1484207 0.4024269] Actual [1.4545763  0.40429106 0.30345342]
Predicted [0.72522336 0.1486159  0.30218923] Actual [1.25727    0.2505553  0.08909374]
Predicted [0.7041166  0.20499873 0.49601766] Actual [0.2865521  0.00998913 0.03110104]
Predicted [0.4779874  0.20255388 0.2433021 ] Actual [-0.05998774  0.12393064  0.03849726]
Predicted [0.216334   0.05174291 0

In [63]:
#R-SQUARED METRIC
R_residual=((outputs[:,1]-y[:,1])**2).sum()
R_total=((outputs[:,1]-np.average(y[:,1]))**2).sum()
print(R_residual)
print(R_total)

[3.56757969e-01 8.95342696e-03 5.72372712e-02 1.18952291e-02
 8.56426507e-02 2.53164113e-01 3.09223360e-05 8.64127219e-01
 2.83073604e-01 1.74360096e-01 2.89417237e-01 8.62240122e-05
 7.75938570e-01 3.63653183e-01 1.56628296e-01 4.78335842e-02
 1.64225078e+00 1.89962927e-02 4.74485606e-02 3.88338268e-01
 1.03762053e-01 5.82522452e-01 2.16255672e-02 1.41527737e-02
 7.38083050e-02 4.22585988e-03 4.40679528e-02 1.16609707e-02
 9.63715836e-03 2.14951802e-02 1.00110084e-01 1.19719312e-01
 2.65548527e-02 2.53476590e-01 3.11003942e-02 3.43393013e-02
 8.25931072e-01 1.04353040e-01 6.14966211e-08 2.92252353e-03
 4.24306840e-02 3.07953358e-02 4.49712249e-03 6.37858137e-02
 7.15103596e-02 4.18127999e-02 9.82849021e-03 4.69323695e-02
 3.52920890e-02 7.80951988e-04 4.12587747e-02 1.73741137e-04
 5.46701672e-03 3.44936103e-02 3.07394892e-01 4.81519522e-03
 4.43742871e-02 9.05168056e-02 8.67739618e-02 2.98744068e-02
 3.08963768e-02 1.76581562e-01 1.48206758e+00 4.00136232e-05
 3.59684005e-02 1.195970

In [0]:
R_squared=1-(R_residual/R_total)
print(R_squared)

In [54]:
df.iloc[150,:]

ccx        -3.525993
ccy        -1.176824
ccz         0.833231
U1          0.210105
U2          0.592905
U3          0.114255
distance    3.809438
Name: 276269, dtype: float64

In [0]:
O = np.array([
[[1,2,3], [4,5,6]],
[[3,8,9], [2,9,4]],
[[7,1,3], [1,3,6]],
[[5,4,2], [6,9,8]]
])

In [56]:
O

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 8, 9],
        [2, 9, 4]],

       [[7, 1, 3],
        [1, 3, 6]],

       [[5, 4, 2],
        [6, 9, 8]]])

In [0]:
O=np.delete(O,1,2)

In [58]:
O

array([[[1, 3],
        [4, 6]],

       [[3, 9],
        [2, 4]],

       [[7, 3],
        [1, 6]],

       [[5, 2],
        [6, 8]]])